meterName: 
    Values: 
        key1: data1, Raw
    Connection:
        Type: Port
        SetUp:
            port: /dev/ttyUSB0
            baudrate: 50
            bytesize: 8
            parity: N
            stopbits: 1
            EOF: 0
            error: 0
            break: 0
            event: 0
            xonxoff: True
            XON: 0
            XOF: 0
            rtscts: True
            dsrdtr: True
            timeout: 0
            writeTimeout: 0
            interCharTimeout: 0
    Communication:
        CRC: CRC16_Modbus_LittleEndian
        Echo: True
        MaxDepth: 0
        MaxTry: 0